name: microtube
services:
  fe:
    image: ${FRONT_END_IMAGE:-registry.local/microtube/front-end:latest}
    container_name: microtube-frontend
    ports:
      - 80:80
      - 443:443
  dev-fe:
    build:
      context: .
      target: development
      args:
        MAIN_BACKEND_SERVER_ADDRESS: http://localhost:8080
        MAIN_BACKEND_SERVER_BASE_PATH: /api/v1
    container_name: microtube-fe
    ports:
      - 5173:5173
    develop:
      watch:
        - action: rebuild
          path: .
